### ISSUE TITLE
caves or underground features do not spawn when b:caves enabled

### ISSUE THREAD

**Issue by j4ix** [BuildTheEarth/terraplusplus#17]
**Describe the bug**
underground features do not spawn when b:caves enabled

**To Reproduce**
Describe the steps it takes to reproduce the bug
Example:
1. set b:caves to true in terra++ conf
2. join the game
3. teleport to a location terra121 would typically generate caves or underground features

**Expected behavior**
terra121 would generate these caves, terra++ says its a feature if enabled

**Screenshots**
world generated with terra121 and b:caves:true
![2021-01-23_10 22 34](https://user-images.githubusercontent.com/34204597/105606095-5390a300-5d65-11eb-8a98-878a166d2205.png)

world generated with terra++ and b:caves:true
![2021-01-23_10 24 56](https://user-images.githubusercontent.com/34204597/105606111-63a88280-5d65-11eb-8213-fa5213b10072.png)

**Error Logs**
n/a.

**Terra121 or Terra++ (please complete the following information):**
 - terra++
 - build #36 doWater always enabled (terraplusplus-0.1.405-1.12.2.jar)

**Version (please complete the following information):**
 - i took out every single mod except the three that could potentially cause the problem, cool

**Comment by rudeyeti** [comment]
Caves have been disabled and are only accessible with a custom CWG Preset, to my knowledge. There is no caves option in the config. It has been removed, so if it still appears for you then that means that your config file must be corrupted.

**Comment by j4ix** [comment]
then there's an error in readme.doc.
it claims strongholds etc have the ability to generate underground when enabled.
this is not true.

**Comment by rudeyeti** [comment]
The readme is still correct. It says that the option is with the CubicWorldGen settings, and not the config of TerraPlusPlus itself.

**Comment by j4ix** [comment]
feature not actually a feature of terra++ and requires unorthodox methods to used

**Comment by rudeyeti** [comment]
Do you need to use caves? It's still possible to use them, but it's just more complex than before.

**Comment by j4ix** [comment]
im trying to get as close to smp playthrough as possible in my city, dm me if you can help make the caves gen.

**Comment by rudeyeti** [comment]
We removed it as a feature since it's never going to be used. Caves are practically useless, and TerraPlusPlus is specifically made for the BuildTheEarth project. Since any non-outline structures aren't very helpful, they can just hurt buildings and not help it. That's why we made the decision to remove it, sorry. It's probably easiest for you to just use normal Terra121, with the caves option in the config.

**Comment by j4ix** [comment]
you're absolutely right, thank you

**Comment by rudeyeti** [comment]
No problem, but in the future we'll provide a guide on how to change the settings for caves and such. Though it's not our top priority at the moment.

**Comment by j4ix** [comment]
main feature i'm going to end up needing for what i'm doing is stronghold and ore generation (and stuff like mineshafts and dungeons but end is reachable without) to make all of the survival 1.12.2 gameplay available, so i'll definitely be using terra121 unless you guys decide to work on it. only mentioning to provide better context for my concern with the cave gen
