### ISSUE TITLE
Incorrect tpll coordinate shows 'terra121.errors.numbers'

### ISSUE THREAD

**Issue by ItzSwirlz** [BuildTheEarth/terraplusplus#22]
**Describe the bug**
/tpll to a location, and add a number or basically anything that has a letter in it that isn't correct.
Instead of showing the normal message, it just says 'terra121.errors.numbers'

It is likely that the fork changed the schema keys; and it was looking for terraplusplus.errors.numbers maybe? or it should have been?

**Expected behavior**
It shows the correct default message

**Screenshots**
![2021-02-13_13 14 42](https://user-images.githubusercontent.com/24401303/107857636-84f90d80-6dfd-11eb-809c-d7d5d63d229a.png)

**Error Logs**
Shouldn't be needed

**Version (please complete the following information):**
 - What version of TerraPlusPlus are you using? Unstable Feb 13 2021 build, 0.1.518
 - What version of the BTE Modpack or Server pack are you running? (If applicable) BTE New Jersey, latest

**Comment by rudeyeti** [comment]
I'll try to fix this now.

**Comment by ItzSwirlz** [comment]
This is because my client updated, but not the server which is still on T121. Closing.
