### ISSUE TITLE
problem with mushroom generation in swamp biomes

### ISSUE THREAD

**Issue by Agrrox** [BuildTheEarth/terraplusplus#26]
**Describe the bug**
Currently high amount of mushrooms are generating in swamp biomes. Is there way to address this issue?

**To Reproduce**
global but I can provide location of the screenshot:
`/tpll 48.16612, 17.14252`

**Expected behavior**
Remove or reduce the amount of mushrooms.

<details>
<summary>Screenshots</summary>

![2021-03-03_19 53 35](https://user-images.githubusercontent.com/10901821/110023623-aaf33d00-7d2d-11eb-9075-8205a7b3bd3e.png)

</details>

**Version (please complete the following information):**
T++ 1.0.527
 T++ addon - customtreerepo
cc 1855
cwg 145

**Comment by DaMatrix** [comment]
i can add an option to the world generator settings to disable vanilla population features individually, with mushrooms being one of them. is that good?

**Comment by Agrrox** [comment]
If you think thats appropriate solution, then I would like to be able to disable these blocks:
39 Brown Mushroom (minecraft:brown_mushroom)
40 Red Mushroom (minecraft:red_mushroom)
86 Pumpkin (minecraft:pumpkin)

**Comment by DaMatrix** [comment]
Resolved in 8b73944ea5844b54048e6befeb17d6087a1e9aec.
