### ISSUE TITLE
3D buildings from a lidar dataset

### ISSUE THREAD

**Issue by RRyyas** [BuildTheEarth/terraplusplus#27]
**Is your feature request related to a problem? Please describe.**
In most cities around the world, 3D buildings doesn't exist on Google Earth. That makes recreating buildings as part of the BTE project quite difficult, and it makes it undesirable for some people to recreate said buildings.

**Describe the solution you'd like**
 However, if there is Lidar data available for the area of interest, there should be a workaround for the lack of 3D in Google Earth, by extracting the building heights from an existing lidar dataset, and displaying it ingame by raising the ingame OSM brick outline to the height that's outputted. This is done by subtracting the digital surface model (absolute height of lidar points) by the digital elevation model (height of the ground points).

**Describe alternatives you've considered**
If it's not possible to render 3d buildings ingame, there should be another tool where you could show the heights of buildings on a 2D map, that could be shareable in some form.

**Comment by DaMatrix** [comment]
this is beyond the scope of terra++ (imo the building outlines are already out of scope, but they were already there when i took over development so now i have to keep them), but there's nothing stopping you from making an addon mod which does that.
