### ISSUE TITLE
how to disable roads in TerraPlusPlus?

### ISSUE THREAD

**Issue by EduardUkreinian** [BuildTheEarth/terraplusplus#28]

**Comment by DaMatrix** [comment]
- download [osm_no_roads.json5](https://raw.githubusercontent.com/BuildTheEarth/terraplusplus/master/src/main/resources/net/buildtheearth/terraplusplus/dataset/osm/osm_no_roads.json5)
- move it to `terraplusplus/config`
- rename it to `osm.json5`
