### ISSUE TITLE
Please send a config in which roads, building outlines and footpaths are disabled

### ISSUE THREAD

**Issue by EduardUkreinian** [BuildTheEarth/terraplusplus#30]
Please send a config in which roads, building outlines and footpaths are disabled

**Comment by DaMatrix** [comment]
- download [osm_no_roads_or_buildings.json5](https://raw.githubusercontent.com/BuildTheEarth/terraplusplus/master/src/main/resources/net/buildtheearth/terraplusplus/dataset/osm/osm_no_roads_or_buildings.json5)
- move it to `terraplusplus/config`
- rename it to `osm.json5`
