### ISSUE TITLE
OSM World Gen Out of Date

### ISSUE THREAD

**Issue by Tysseract** [BuildTheEarth/terraplusplus#31]
**Describe the bug**
Openstreetmap data is at least 2 months old.

**To Reproduce**
1. Make an edit to opestreetmap. Make sure to find something that's wrong enough to actually warrant an edit (add a sidewalk or move a creek to fit the satellite imagery)
2. wait a while (osm changes are minutely but give Overpass API at least a couple hours to catch up.
3. Check that your edit has taken effect on https://osm.org
4. go to the location in-game with /tpll
5. select the region in question with the world edit wand and do //regen

**Expected behavior**
the terrain should change to reflect the new path/building or moved creek

**Screenshots**
https://i.imgur.com/oOG95mk.jpg
This is a new world on a fresh install of the BTE pack on which I used //regen. This trail was added over a month ago (https://www.openstreetmap.org/way/919035688). Notice the difference between the OSM map in the top left and the journeymap in the top right.

**Version (please complete the following information):**
 - What version of TerraPlusPlus are you using? v1.1.0.578-1.12.2
 - What version of the BTE Modpack or Server pack are you running? 1.19.2-windows

**Comment by Coppertine** [comment]
Terraplusplus is using a mirror version hosted by @DaMatrix. Due to this, the OSM data has been outdated since November of 2020. I'd highly suggest using the tpll method instead.

**Comment by Tysseract** [comment]
Gotcha. I appreciate the hosting as it must take a significant load off OSM servers, but a lot can change in six months. 
I've been editing osm in my area a lot recently and I can see why the /tpll method is the standard (many roads and building outlines are slightly off) but I've made significant progress in my area with creeks, building outlines, roads, etc. 
There have also been a lot of real world-changes to the roads in my area (freeway work, new roundabouts, etc.) that I added via GPS trace but are not yet on google satellite imagery.

**Comment by Tysseract** [comment]
I guess my request, then, is for an update to the database... I think a quarterly or semiannual update would be very beneficial for the following reasons:
- OSM data is useful
  - It is essential to orient people in-game
  - It can be a very good aid when google earth is fuzzy or missing data
  - It is opensource (there are no issues with the use of Google's copyrighted work)
  - Natural features such as streams and shorelines rely on accurate and updated OSM data
  - It is much easier to accurately map a hiking trail and have it auto-generate path blocks than to manually place path blocks along a very long, mundane, and windy route
- Real-world changes would be reasonably up to date in-game
  - Road changes/additions and road-way accuracy adjustments are not uncommon
  - Creeks and Rivers can change route drastically in a year (My area had a mudslide in 2017 but I only adjusted the OSM streams to match in the last few months)
  - New or improved building outlines will be added to the map
- A public/predictable update cycle helps people, like myself, know why things appear out of date and when they will be fixed.
- At a little over 100GB compressed, I don't think a semiannual update of [Planet.osm](https://wiki.openstreetmap.org/wiki/Planet.osm) is unreasonable

**Comment by Tysseract** [comment]
Alternatively (although this, of course, would take a significant effort in backend development) https://planet.openstreetmap.org/ does have weekly changeset diffs of ~5GB which could be automatically retrieved and incorporated

**Comment by DaMatrix** [comment]
the system i'm using for OSM (which i made specifically for terra++) is https://github.com/DaMatrix/TerraPlusPlusOSMTileGen. while it *does* support automatic (minutely) updates, they currently aren't running - i need to get access to better hardware to run it on. currently it's still using the same version of `planet.osm` as it was initially prepared with (from mid-november).

i certainly plan on getting this working properly at some point in the near future, but am currently facing some uncertainty regarding my current housing situation, so getting new hardware is a bit iffy for the time being.

**Comment by Tysseract** [comment]
Totally understand! Let me know if there's anything I can do to help... My internet is like 15mbps up so I can't really offer my hardware but I'll support the patreon

**Comment by FireFragment** [comment]
> the system i'm using for OSM (which i made specifically for terra++) is https://github.com/DaMatrix/TerraPlusPlusOSMTileGen. while it _does_ support automatic (minutely) updates, they currently aren't running - i need to get access to better hardware to run it on. currently it's still using the same version of `planet.osm` as it was initially prepared with (from mid-november).
> 
> i certainly plan on getting this working properly at some point in the near future, but am currently facing some uncertainty regarding my current housing situation, so getting new hardware is a bit iffy for the time being.

Just curious, why we don't use Overpass API?

**Comment by DavixDevelop** [comment]
> > the system i'm using for OSM (which i made specifically for terra++) is https://github.com/DaMatrix/TerraPlusPlusOSMTileGen. while it _does_ support automatic (minutely) updates, they currently aren't running - i need to get access to better hardware to run it on. currently it's still using the same version of `planet.osm` as it was initially prepared with (from mid-november).
> > 
> > i certainly plan on getting this working properly at some point in the near future, but am currently facing some uncertainty regarding my current housing situation, so getting new hardware is a bit iffy for the time being.
> @DaMatrix 
> 
> Just curious, why we don't use Overpass API?

Read this PR why we stopped using it.
https://github.com/BuildTheEarth/terraplusplus/pull/13

**Comment by FireFragment** [comment]
> the system i'm using for OSM (which i made specifically for terra++) is https://github.com/DaMatrix/TerraPlusPlusOSMTileGen. while it _does_ support automatic (minutely) updates, they currently aren't running - i need to get access to better hardware to run it on. currently it's still using the same version of `planet.osm` as it was initially prepared with (from mid-november).
> 
> i certainly plan on getting this working properly at some point in the near future, but am currently facing some uncertainty regarding my current housing situation, so getting new hardware is a bit iffy for the time being.

I understand, that the situation doesn't allow updates every minute, but what about updating `planet.osm` in longer intervals, eg. weekly or monthly? I contribute to OpenStreetMap and it would be nice to see my changes in Minecraft.

**Comment by lesharko** [comment]
Well now it's even more outdated... glad this project died out
