### ISSUE TITLE
No world generation

### ISSUE THREAD

**Issue by Gamingyaaa** [BuildTheEarth/terraplusplus#48]
I put the world generation on build the earth and nothing spawned in, just a small cube of grass maybe 2x2 chunks and and then infinite ocean, teleporting to land via Minecraft coordinates spawns me in void and I can't move there is just nothing, also the player doesn't move on the terra map from that addon.

**Comment by PS-Dane** [comment]
Same issue here.

**Comment by SmylerMC** [comment]
Terra++ currently only works with preset that are close enough to a 1 to 1 scale, because it can only sample data a fixed scale optimized for 1 to 1 world. This is one the improvements planned for Terra++ 2.0.
