### ISSUE TITLE
Almost no world generation

### ISSUE THREAD

**Issue by JustSomeGuy2000** [BuildTheEarth/terraplusplus#50]
Just spawns a square mushroom island with a small forest in the middle and infinite ocean on Planet Earth setting.
Using 1.12.2 version of mod with 1.12.2 Minecraft Java and CurseForge.
CubicChunks, CubicWorldGen, Journeymap and MalisisCore installed.

**Comment by vaporrrr** [comment]
That's intentional, you spawn at 0, 0. Use /tpll lat long
