### ISSUE TITLE
LittleTiles door incompatibility with Terra Plusplus

### ISSUE THREAD

**Issue by Potsukin** [BuildTheEarth/terraplusplus#53]
LittleTiles door not working properly in Terra PlusPlus world.

https://www.youtube.com/watch?v=jOKp_CFbkWE

terraplusplus-1.1.0.619-1.12.2
CubicChunks-1.12.2-0.0.1249.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.169.0-SNAPSHOT-all
LittleTiles_v1.5.58_mc1.12.2
CreativeCore_v1.10.70_mc1.12.2

I have also put it out as an issue on the LittleTiles Github page. Here is the link：

https://github.com/CreativeMD/LittleTiles/issues/827

**Comment by SmylerMC** [comment]
Hello,
I really can't see how that would be an issue with Terra++ since it only affects world generation, does the bug also occur on vanilla worlds ?

**Comment by Potsukin** [comment]
LittleTiles is stable in Vanilla Minecraft with no bugs and works fine in CubicWorld below 255 meters. But only in worlds created with Terra PlusPlus it behaves strangely.

**Comment by CreativeMD** [comment]
Turns out it's the coordinate distance, which makes the doors bug out.

**Comment by SmylerMC** [comment]
Ok, I should have figured it was something like that, other mods have the same problem (even vanilla does).
There isn't much we can do on Terra++'s side, I'm closing this issue.

Have a nice day.
