### ISSUE TITLE
Please support minetest version

### ISSUE THREAD

**Issue by Pantyhose-X** [BuildTheEarth/terraplusplus#55]
https://www.minetest.net/
Minetest 
An open source voxel game engine. Play one of our many games, mod a game to your liking, make your own game, or play on a multiplayer server.

Available for Windows, macOS, GNU/Linux, FreeBSD, OpenBSD, DragonFly BSD, and Android.

Enormous Maps
With 62,000 × 62,000 × 62,000 blocks, there’s no running out of space. You can mine 31,000 blocks down, or build 31,000 blocks up.

**Comment by XboxBedrock** [comment]
Minecraft world space is plenty for BTE, if you really wanted to you can do this yourself on your own accord somewhere else but this likely won't happen in the foreseeable future, this is a java Minecraft mod and while it is abstracted enough to support multiple versions of Minecraft, this is far from some multi-language library. This is completely unrelated to the core project hence closing the issue. I hope you understand why.
