### ISSUE TITLE
Unrecognized character escape 'q' when creating a world with custom lidar data installed

### ISSUE THREAD

**Issue by ShinyJustyZ** [BuildTheEarth/terraplusplus#56]
When I try to create a t++ world using custom lidar data, it just crashes on the button press and the crash logs gives the error message: 
`net.buildtheearth.terraplusplus.dep.com.fasterxml.jackson.databind.JsonMappingException: Unrecognized character escape 'q' (code 113)`
This doesn't happen when the lidar data isn't there and the world loads normally.
Logs link: https://pastebin.com/zDXFHv3c
My heights.json file (yes, the path is correct): https://pastebin.com/7wG6U06v

**Comment by DavixDevelop** [comment]
Replace all `\` with `/` in the URL

**Comment by ShinyJustyZ** [comment]
New error: `net.buildtheearth.terraplusplus.dep.com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('"' (code 34)): was expecting comma to separate Object entries`
Heights.json: https://pastebin.com/j7ccRBy0
Crash logs: https://pastebin.com/xqGjfFXE

**Comment by DavixDevelop** [comment]
You forgot to add commas at the end to the objects in the `"bounds"` object. Look at the endings of objects  in the `"zoom"` object bellow for reference. In JSON, every element/object is separated by a comma.

**Comment by ShinyJustyZ** [comment]
That fixed it! Thank you!
