### ISSUE TITLE
World is flipped in default setting

### ISSUE THREAD

**Issue by DrBlock21** [BuildTheEarth/terraplusplus#59]
I'm not sure if this is intentional, but the world is mirrored. If I wanted to turn left in the real world, I would turn right in game. When I look east according to my f3 menu, the map says I look west. I am using the latest version of Terra++. Thank you.

**Comment by LencoDigitexer** [comment]
![изображение](https://github.com/BuildTheEarth/terraplusplus/assets/44779327/8f5a0515-924b-4ce4-a579-be7e63d1099d)


In the world generation settings, set Vertical Flip
