### ISSUE TITLE
i cant get the altitude to work

### ISSUE THREAD

**Issue by someguy11223344** [BuildTheEarth/terraplusplus#60]
**Describe the bug**

**To Reproduce**
Describe the steps it takes to reproduce the bug
Example:
1. Join the game
3. Execute command `/tpll...`
4. See Error Log

**Expected behavior**

**Screenshots**

**Error Logs**
If applicable, paste your server logs into `https://mclo.gs/` and include the link here.

**Version (please complete the following information):**
 - What version of TerraPlusPlus are you using?
 - What version of the BTE Modpack or Server pack are you running? (If applicable)

**Comment by Nudelsuppe42** [comment]
Please fill out the provided template
