### ISSUE TITLE
/terra tissot text formatting is broken

### ISSUE THREAD

**Issue by SmylerMC** [BuildTheEarth/terraplusplus#9]
**Description**
`/terra tissot` chat formatting does not actually format the numbers in the text component (tested in singleplayer).
![Screenshot_20210103_132946](https://user-images.githubusercontent.com/19222559/103478543-c4c4e200-4dc7-11eb-84a1-0eefa17b3591.png)
Other commands may be affected as well.
I did not have time to test this further and probably won't have time to investigate and fix myself in the near future, maybe @noahhusby already has an idea of what is wrong ? Also is there a specific reason to force the translation to happen on the server side ?

**Version:**
I believe this was introduced in [f4c17534c358979a2d0dec88e64af816a32515ed](https://github.com/BuildTheEarth/terraplusplus/commit/f4c17534c358979a2d0dec88e64af816a32515ed)

**Comment by noahhusby** [comment]
Looks like my text formatting replacement isn't working quite right. I'll take a look.

Translation occurs on the server-side to compensate for CubicChunks Vanilla support. There are use cases where T++ likely isn't installed on the client-side, so therefore server-side translation is necessary.

**Comment by SmylerMC** [comment]
CC vanilla support is not the actual problem, the mod can be server side only.
What about checking for the mod's presence on the client ?

**Comment by SmylerMC** [comment]
Also why do the placeholders need to be changed ?

**Comment by noahhusby** [comment]
Turns out the issue was that I never pushed my latest code so the disaster you are witnessing is my test code.

**Comment by SmylerMC** [comment]
Solved
